### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by sandyflute** [hastings24/mammoth#1]
Hi,

Thanks for sharing the code. This is amazing. 

When i try to run main.py from the root directory(where the code is cloned), i get this error.

`mammoth$ python ./utils/main.py`

> Traceback (most recent call last):
>   File "./utils/main.py", line 2, in <module>
>     from datasets import NAMES as DATASET_NAMES
> ModuleNotFoundError: No module named 'datasets'

am i missing something here ?

Thanks.

**Comment by mbosc** [comment]
My guess is that your PYTHONPATH env variable is not set to the root directory.
Try running `export PYTHONPATH=<your_path>/mammoth`, that should do the trick.
